[tool.poetry]
name = "coc-ruff"
version = "0.1.0"
description = ""
authors = ["yaegassy <yosstools@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ruff-lsp = "0.0.61"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
